### ISSUE TITLE
Add action for slot select: video format: {videoFormat} 

### ISSUE THREAD

**Issue by LikeThisReview** [bitfocus/companion-module-bmd-hyperdeck#103]
[Enhancement 6] Add action for slot select: video format: {videoFormat} 

Please add action for selecting output video format for a timeline, similar to slot select: slot id: {slot ID} and slot select: video format: {videoFormat} 
Commands may be combined and should support variables.

Use case. Currently Hyperdeck device might switch to a different output video format when the file format (codec) is changed.
As far as I can tell Hyperdeck takes the output video format from the first clip it can find with the new codec, based on “closest to setting Default (video) Standard” (in Seup menu LCD display).

Example. 
Set Default (video) Standard to 1080p60 in the Setup menu. 
Connect only one empty disk to the Hyperdeck device (to keep it simple). 
Record a clip 1 with name Z in ProRes 180p60 (SDI input ATEM Mini) and then clip 2 with name A in ProRes 1080p5994 (HDMI input iPad). 
(The last recorded clip is now on the timeline and can be played back). 
Change codec to H.264medium (results in an empty timeline).
Change codec back to ProRes. 
Now the output video format has been automatically changed to **1080p60** and the first clip is on the timeline. 
The 1080p5994 can now only be played back when the video standard is changed in the Setup menu, or a new clip is recorded from the 1080p5994 input (if available). 
(There is no issue when a disk has clips only in 1 fileFormat - videoFormat).

Tested with HyperDeck Studio HD Plus and Companion v3.1.

**Comment by Julusian** [comment]
This is implemented, and will be in the beta builds later today

**Comment by LikeThisReview** [comment]
Tested on v3.2.0+6231 and it works as expected (even better than my
workaround). Many thanks !!

Op vr 6 okt 2023 om 21:10 schreef Julian Waller ***@***.***>:

**Comment by LikeThisReview** [comment]
Julian, Many thanks! Did a quick test with "unchanged", 1080p60 and
1080p5994 which was successful. Late next week I will do a test for the
other video formats. Regards, Nico Wasmus

Op vr 6 okt 2023 om 21:10 schreef Julian Waller ***@***.***>:
