### ISSUE TITLE
Timecode doesnt update on button

### ISSUE THREAD

**Issue by tubalois** [bitfocus/companion-module-bmd-hyperdeck#104]
Hi

Not sure if it's a bug or if it's me:
I'm trying to have the TC of my hyperdeck on one button of the streamdeck to monitor it. Unfortunately the timecode doesn't update while playback is on, in fact the TC stays at the same value as the timecode when the hyperdeck connected.
Also in the variables tab the TC is the TC at the connection between the devices and will not be updated when changed in the hyperdeck

Thanks!
Blackmagic Hyperdeck Studio Mini
Companion [(3.0.1+6068-stable-a05a9c89)](https://bitfocus.io/companion/)
Win11
MS Edge 117.0.2045.43

**Comment by tubalois** [comment]
Nevermind, after a day of searching i found it one minute after this post...

**Comment by Julusian** [comment]
It sounds like you figured it out? If not I can reopen this
