### ISSUE TITLE
Issues controlling multiple hyperdeck studios

### ISSUE THREAD

**Issue by ishboo** [bitfocus/companion-module-bmd-hyperdeck#105]
I have two HyperDeck studios. The first one (and lowest IP) works just fine. I can control the second one but when I try to send commands to them together, the second one locks up. The device functions but whatever service handles the network control seems to crash and the whole device needs to be power cycled. Is the command protocol broadcast or multicast? It seems that it's getting conflicting commands but I don't know why it would be processing both.

**Comment by Julusian** [comment]
The commands is sent over a direct tcp connection to the device, I don't think there could be conflicting traffic here. 

Is this with the old 1u, dual ssd, pale/mid grey models?
I have had those crash on me before, but normally only once during the week they are powered on for.

**Comment by ishboo** [comment]
After a lot more troubleshooting we determined it was an issue with the drive and the BM firmware that would brick the interface, it felt like an issue with the companion control of it but after this testing I don't believe the bug is related to companion so I'll close this issue. Thank you for the response.
