### ISSUE TITLE
Issue $(hyperdeck:countdownTimecodeHMS) displaying --:--:--:--

### ISSUE THREAD

**Issue by LikeThisReview** [bitfocus/companion-module-bmd-hyperdeck#108]
v3.2.0+6439. The variable $(hyperdeck:countdownTimecodeHMS) displays --:--:--:-- in preview mode. In playback mode it ia working as expected. It should provide countdown timecode, regardless the hyperdeck status (as before).

Regards, Nico Wasmus

**Comment by sphlabs** [comment]
This is a duplicate of #109 and a fix is in-progress.

**Comment by LikeThisReview** [comment]
Ok, thanks for the update.

Op za 9 mrt 2024 om 20:25 schreef Stephen Harrison ***@***.***
