### ISSUE TITLE
bug: Feedback of T/C not working - but Format and playback/rec control is ok.

### ISSUE THREAD

**Issue by lotech** [bitfocus/companion-module-bmd-hyperdeck#25]
I'm working through a film cart setup with 20 Hyperdecks on it. 2 are record decks. Control is working well for all of them - playback/record control is working on all with feedback of state. Also input format is also feeding back properly. 
Unfortunately - based on the current 2.1.1 build of Companion does not receive T/C feedback - it just reports 00:00:00. This is in playback and record mode.

**Comment by baltedewit** [comment]
Hi, thanks for opening an issue. Just for completeness I'd like to know what firmware version your hyperdecks are running and (if this is possible for you to check) whether the problem persists with only 1 hyperdeck connected. TIA.

**Comment by lotech** [comment]
7.1.1 - the latest. I've checked all the decks so they're running the newest. Most are Hyperdeck Pro's but some the 12G models. The ones I've tested as far as TC goes are all Pro's - the other racks are made up of 4 pro's and 2 12G's.

**Comment by sphlabs** [comment]
Also for completeness, just to confirm that you have enabled the polling option on the setup page for each Hyperdeck instance?

--    
www.linkedin.com/in/sharrison
www.stephenharrison.me.uk

**Comment by lotech** [comment]
Facepalm. Sorry - that was it. Won't be polling all 20 - just the 2 record decks. Thanks.
