### ISSUE TITLE
Format Hyperdeck Media 

### ISSUE THREAD

**Issue by mag333** [bitfocus/companion-module-bmd-hyperdeck#26]
I miss the feature to format Hyperdecks media via stream deck.. Any idea?

**Comment by Julusian** [comment]
I have to question, is this really a good idea to have on a streamdeck?
This operation is generally rare enough that I don't see much benefit, and as companion doesnt support any kind of confirmation it sound like a massive risk to have it there as it would be so easy to trigger and accidentally wipe your recordings

**Comment by sphlabs** [comment]
I didn’t implement the feature for that very reason. It seemed like far too dangerous an operation to be triggered accidentally, and didn’t seem to fit into the remit of operational, ‘live’, commands that Companion is suited to.

**Comment by RaulDuke77** [comment]
I get your point.
But you don´t have to make a button with this command on your Stream Deck, so i think you only use that function if if you 
benefit from that command. And you can move the "format button" on another page, away from the normal control buttons.
In our studio environment we would would be very happy to have such a command with multiple rackmounted Hyperdeck Minis.

**Comment by mag333** [comment]
What if the button has to be hit 3 times within 2 seconds? I guess this can´t be happen accidentally...
We are running 6 hyperdecks mini in our studio environment. It´s very annoying to navigate 6 times through the menu before production...

**Comment by AZJAYNES** [comment]
This would be  very helpful add like the others have said i'm constantly on shows that have numerous record decks and it would be so great to send a format command for slot one on one keystroke and slot 2 on another would make my job so much easier.  This button for me would be on a different page so its intentional when its triggered.  I was looking at ways to code this on my current show but ran out of time before we went live.  PLEASE ADD THIS option.

**Comment by sphlabs** [comment]
If this were implemented, would you want any built-in safety mechanism (if even possible), or would you treat this as a very sharp tool, and build any level of protection into your own workflow (e.g. put on another page, or preceded with a long delay with a nearby "Abort all delayed actions" button)?

**Comment by AZJAYNES** [comment]
It would be nice to have a safety measure but I’d likely be placing on an ancillary page and not near my operating button set or a secondary stream deck.  Thank you for inquiring and can’t wait to see how this is implemented.

Jason Jaynes
623-451-9980

**Comment by sphlabs** [comment]
Format commands have now been added to the master branch. If you have a dev environment the do grab the update and test it out.

**Comment by AZJAYNES** [comment]
I do not have a DEV or currently a unit in my position but ill ask a friend
if hes bored

Thank you

**Comment by PhotoJoseph** [comment]
Greetings. I'm excited to have this feature and am looking for the safest way to implement. I tried a couple things…

1) I set up a key-down to PREPARE, and key-up to CONFIRM, which works nicely, but I'm unsure how to cancel that if you decide not to confirm (i.e. accidentally tapped it). I set an INSTANCE FEEDBACK of FORMAT PREPARED (to make the button red) so I know it's ready and about to format. I like this method as it's a two-tap to do the job, but would like to be able to properly cancel the action.

2) I also tried a delay; setting PREPARE on key-down, then five seconds later a CONFIRM, with a key-up to ABORT ALL DELAYED, which works too. I also set an INSTANCE FEEDBACK of FORMAT PREPARED (make the button red) so I know it's getting ready, and that works OK, but it stays red after aborting. I don't know if there's a way to clear the feedback status? 

I prefer the first option anyway… two taps is better than one for this. Is there a way to cancel the action and refresh the feedback?

Thanks
-Joseph

**Comment by sphlabs** [comment]
I'm with you that a two-step process seems better, and you raise a good point about an aborted format.

As far as I can tell, the format token sent by the deck after a `prepare` action doesn't actually expire - I've left it several hours and still been able to  successfully complete a format `confirm` operation. However, it would be nice for Companion to reset back to a safe state after a period of time, so I'll look into adding that feature.

**Comment by PhotoJoseph** [comment]
Sounds great, thank you! Like others here, I have six of these things, and the built-in format process is tedious, at best. Your tools make using these recorders much more enjoyable! I very much appreciate your efforts here.

**Comment by sphlabs** [comment]
FYI, I've added a timeout setting to the Format Prepare command, so if you change your mind it will revert to a safe state.
