### ISSUE TITLE
Hyperdeck Mini Logging every second or so [BUG]

### ISSUE THREAD

**Issue by shaunus** [bitfocus/companion-module-bmd-hyperdeck#27]
Hyperdeck Mini slot status being logged every second or so (varies 1-3 sec intervals)

1. Connect to Hyperdeck Mini
2. Start recording
3. Go to Companion log
4. Watch scroll of log being filled endlessly with "28. hh:mm:ss instance(hyperdeck): Slot Status Changed"

This seems like a resource hog or something. Doesn't seem like a normal behaviour. It only happens during recording, doesn't matter if there is one or two cards in slots.

 - OSX 10.14.6
 - Browser -- Chrome
 - Companion Version 2.1.1.2603

![image](https://user-images.githubusercontent.com/7552001/94494727-b487e000-01a4-11eb-939f-6c1c956b7845.png)

**Comment by sphlabs** [comment]
I am unable to replicate this with a Hyperdeck Studio.

However, Companion doesn't request slot status change updates; those messages are generated when the Hyperdeck issues a status change notification, which Companion listens for, and responds to.

Is this issue still persisting? Do you have any other decks you can test it with?

**Comment by bryce-seifert** [comment]
I have also seen this with our Minis only, Studio and Studio Pros don't.

**Comment by shaunus** [comment]
It's possible this was only occurring with recording mode set to h264, as I usually use ProRes LT. I only have another Mini to test with.

**Comment by sphlabs** [comment]
Does changing the file format on your Mini make this problem appear/go away?

**Comment by shaunus** [comment]
Just tested last night but hadn’t had a chance to reply yet, yes it did! ProResLT no problem. Today I will retest by switching back to try to reproduce the original problem.

**Comment by shaunus** [comment]
Actually, I spoke too soon. I think I was too focused on executing a successful production (yay!) to notice, but in testing again today, the problem still persists and is reproducible for me, although oddly the duration between slot-status changes seems longer when recording to ProRes LT (4-5secs) than h264 (High) (1-3secs):

![image](https://user-images.githubusercontent.com/7552001/95375089-fe9f4e80-0893-11eb-979f-e63b13fa3acb.png)

**Comment by sphlabs** [comment]
I have now tested this on a Mini, so I know what's going on.

First off, all slot status change messages are async messages generated, and sent, by the Hyperdeck; companion just listens out for them.

It turns out that the Mini has a lower threshold for what it considers a change to slot status, and during recording, whenever the remaining recording time changes (i.e. every second) it issues a slot status changes. The Studios do not do this.

So it's not a bug, and there isn't anything that can be done about it…

**Comment by shaunus** [comment]
Thanks, Stephen, for your investigation into this. Hahaha so it's not a bug
with the Companion module, at least :)

Do you think this causes a resource problem of any kind? I've noticed my
Companion installation gets really slow to respond on the GUI after running
for a while (streamdeck control still perfect).

It seems strange as I don't recall this happening before on earlier builds,
but maybe I just never noticed it.

**Comment by sphlabs** [comment]
I don't think it poses a significant resource issue. The network stack can handle a lot of traffic, so one notification every second won't affect that (polling for timecode updates can be done every 40ms with no ill effect).

It may be worth looking at the logging of this at some point, but that is a separate issue.
