### ISSUE TITLE
Javascript error when disabling Hyperdeck instance

### ISSUE THREAD

**Issue by regionshospitalems** [bitfocus/companion-module-bmd-hyperdeck#28]
I use Companion and a Stream Deck to manage a rack of Blackmagic video equipment.  The Companion app runs in the background, so when I shut down the video equipment rack there is a Companion command to disable the interfaces to all of the Blackmagic devices.  I have had issues with Companion crashing silently when I shut everything down.  Through trial and error I have isolated it to a reproducible situation when I attempt to disable a Hyperdeck instance when the Hyperdeck is already powered off (in a "connecting" or "error" state in Companion).  Attached is the javascript error that results in Companion crashing.

Expected behavior: Companion should gracefully handle this error and disable the Hyperdeck instance even if the Hyperdeck is not currently connected.

![screenshot-remotedesktop google com-2020 12 01-08_33_14](https://user-images.githubusercontent.com/75321031/100754639-eab62b80-33b0-11eb-9b68-2e5d55bd61d8.png)

**Comment by sphlabs** [comment]
Thanks for the report.

Can you confirm which version of Companion you are using?

**Comment by regionshospitalems** [comment]
2.1.1

**Comment by sphlabs** [comment]
I haven't managed to precisely narrow down the conditions to recreate this every time, but I can reproduce the bug by toggling the enable/disable status when the deck is unreachable.

An error event is being emitted by hyperdeck-connection, which is usually caught and logged, but not under some conditions.

```
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 192.168.1.151:9993
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)
Emitted 'error' event on Hyperdeck instance at:
    at Socket.<anonymous> (…/companion/lib/module/bmd-hyperdeck/node_modules/hyperdeck-connection/dist/hyperdeck.js:45:45)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.168.1.151',
  port: 9993
}
```

Any ideas @baltedewit ?

**Comment by baltedewit** [comment]
It looks to me like it's an old socket lingering around. I can reproduce this by enabling the instance with a non-hyperdeck IP address and then waiting for a long time. It seems more consistent since the node 12 upgrade too so that will be good for reproducing.

**Comment by sphlabs** [comment]
This edge-case needs to be handled better by `hyperdeck-connection`, as there is no way for us to know if a connection attempt is still in-flight (and therefore need to wait for it to time-out).

https://github.com/nrkno/sofie-hyperdeck-connection/issues/16

**Comment by sphlabs** [comment]
Latest update should prevent all these crashes happening now.
