### ISSUE TITLE
Countdown instead of countup TC possible?

### ISSUE THREAD

**Issue by ely105** [bitfocus/companion-module-bmd-hyperdeck#32]
This may be a total rookie question but is there a way to create a countdown timer from the variables of Hyperdeck?  I can display the count-up timer variable but would love to create a countdown timer display.  Is there arithmetic possible with variables?

Thanks,
M

**Comment by sphlabs** [comment]
Unfortunately, there doesn't seem to be a way to get clip duration back from the Hyperdeck, only the current timecode of a clip. So there is no way to calculate remaining time.

**Comment by baltedewit** [comment]
It's possible to get the clip duration from the `disk list` command based on which I started to implement this but I found quickly that the display timecode is not guaranteed to start at 0 and so I had to implement the `clips get` command which includes the start timecode to calculate offsets.

_Tl;dr: work in progress._
