### ISSUE TITLE
Hyperdeck control for Shuttle 2

### ISSUE THREAD

**Issue by shonufleroy** [bitfocus/companion-module-bmd-hyperdeck#34]
I want to know if this will control a Blackmagic Hyperdeck Shuttle 2, since there is no Ethernet  port on it.  I just need simple video playback to my Atem Mini Pro, and I see several for sale.

**Comment by baltedewit** [comment]
Sory, the product needs to implement the hyperdeck protocol which is only exposed over ethernet so the Hyperdeck Shuttle series will not work

**Comment by shonufleroy** [comment]
Thank you very much for such a quick answer.  You saved me some money.
