### ISSUE TITLE
timecode is not displayed

### ISSUE THREAD

**Issue by keiakiba** [bitfocus/companion-module-bmd-hyperdeck#38]
Thank you for implementing timecode countdown.
Very convenient.

Bitfocus Companion 2.2.0 (410b6bc3-3110)
Hyperdeck MINI

However, in ProRes 1080p2997, it is displayed in Dynamic Variables, but it is not displayed in 1080p5994.

Is it just my environment? Please consider.
![1080p2997](https://user-images.githubusercontent.com/39714825/110734485-45420c00-826b-11eb-9c62-af69d612375b.png)
![1080p5994](https://user-images.githubusercontent.com/39714825/110734492-483cfc80-826b-11eb-88e9-7d4f448ec421.png)

**Comment by keiakiba** [comment]
variables.js

const frameRates = {
    [VideoFormat.NTSC]: 29.97,
	[VideoFormat.PAL]: 25,
	[VideoFormat.NTSCp]: 29.97,
	[VideoFormat.PALp]: 25,
	[VideoFormat._720p50]: 50,
	[VideoFormat._720p5994]: 59.94,
	[VideoFormat._720p60]: 60,
	[VideoFormat._1080p23976]: 23.897,
	[VideoFormat._1080p24]: 24,
	[VideoFormat._1080p25]: 25,
	[VideoFormat._1080p2997]: 29.97,
	[VideoFormat._1080p30]: 30,
	[VideoFormat._1080i50]: 25,
	[VideoFormat._1080i5994]: 29.97,
	[VideoFormat._1080i60]: 30,
	[VideoFormat._4Kp23976]: 23.976,
	[VideoFormat._4Kp24]: 24,
	[VideoFormat._4Kp25]: 25,
	[VideoFormat._4Kp2997]: 29.97,
	[VideoFormat._4Kp30]: 30,
	[VideoFormat._4Kp50]: 50,
	[VideoFormat._4Kp5994]: 59.94,
	[VideoFormat._4Kp60]: 60,
}
Is it because1080P5994 is not defined?
It seems that you are looking at frame rate with Timecode

I apologize if I'm wrong
Thank you for your consideration

**Comment by sphlabs** [comment]
You are half right in that 1080P5994 is not defined as a valid format, however that is based on supported formats as documented by BMD! So if there are other formats that work but are undocumented, that would explain your problem!

If we can get a definitive list of all the formats that the Mini actually supports, then I'm happy to add support for those, although I don't have access to a Mini myself atm for testing.

**Comment by sphlabs** [comment]
@baltedewit are you able to verify the formats actually available on a Mini -- rather than what is listed in the docs?

**Comment by sphlabs** [comment]
These extra frame rates have now been added.
