### ISSUE TITLE
Starting with build 3098, some Hyperdecks stuck on "Connecting"

### ISSUE THREAD

**Issue by bryce-seifert** [bitfocus/companion-module-bmd-hyperdeck#41]
After upgrading to build 3098 of Companion, which introduced " feat: timecode countdown and select clip from list", around half of my Hyperdecks are stuck on "Connecting." 

I'm able to send actions to them, and although the button variables don't initially load once I send an action they do. So they're obviously connected, but something is not right with the status. 

Deleting and re-adding the instance has the same result.

Out of my 7 Hyperdecks:
OK: 2 Studio Pros, 1 Mini
Stuck on Connecting: 3 Studios, 1 Mini

**Comment by baltedewit** [comment]
Sorry to hear it's not quite living up to expectations. What firmware versions are these decks on? It would be very helpful if you could connect to one of the failing decks over TCP (using something like putty or netcat) and give me the output from the `clips get` command

For what it's worth I ran all my testing on a mini so we should certainly somehow be able to get it to work again :)

**Comment by sphlabs** [comment]
It sounds like it might be firmware related, given you have one Mini that works and one that doesn't.

Most of my testing is on a Studio, so would be good to get to the bottom of this.

**Comment by bryce-seifert** [comment]
Ok, updating to 7.1.3 firmware on one of the problem decks  and updating Companion again I got this bug on all of the Hyperdecks. I confirmed it's showing the "Connected to a Hyperdeck Studio" in the logs, but the instance status is stuck on Connecting.

**Comment by ColinMulcahy** [comment]
Hi, I'm having the same issue with. both Hyperdeck Studio. 12G's (6) and Hyperdeck Studio Mini's (2).

Status shows connecting but can control decks.

**Comment by sphlabs** [comment]
This was being caused by code attempting to get a list of clips before setting the connected status. There was an assumption that there would be clips to return, and when there weren't the code got stuck waiting.

Should now be fixed.
