### ISSUE TITLE
Feature Request: Remote Control - Action and Feedback

### ISSUE THREAD

**Issue by ColinMulcahy** [bitfocus/companion-module-bmd-hyperdeck#42]
Hi,

Is it possible to implement the following features:

**ACTION** 

To enable or disable remote control:

remote: enable: {“true”, “false”} ↵

The current remote control state may be overridden allowing remote access over ethernet irrespective of
the current remote control state:

remote: override: {“true”, “false”} ↵

The override state is only valid for the currently connected ethernet client and only while the connection
remains open.

The “remote” command may be used to query the remote control state of the deck by specifying no
parameters:

remote↵

**FEEDBACK**

The deck will return the current remote control state:

210 remote info:↵
enabled: {“true”, “false”}↵
override: {“true”, “false”}↵
↵

**Comment by sphlabs** [comment]
I have added an action for setting remote state. Feedback will need to wait for an update to the hyperdeck-connection library

https://github.com/nrkno/sofie-hyperdeck-connection/issues/15
