### ISSUE TITLE
Feature Request: Video Input - Feedback

### ISSUE THREAD

**Issue by ColinMulcahy** [bitfocus/companion-module-bmd-hyperdeck#43]
Hi,

Is it possible to implement the following features:

**ACTION**

Setting the action is already implemented for SDI and HDMI in the module.

configuration: video input: {“SDI”, “HDMI”, “component”}↵

**FEEDBACK**

The "configuration" command may be used to query the current configuration of the deck:

configuration↵

The server returns the configuration of the deck:

211 configuration:↵
video input: {“SDI”, “HDMI”, “component”}↵
↵

**Comment by sphlabs** [comment]
This will require an update to the `hyperdeck-connection` module to support notification of configuration changes.

https://github.com/nrkno/tv-automation-hyperdeck-connection/issues/13
