### ISSUE TITLE
Feature Request: Audio Input - Feedback

### ISSUE THREAD

**Issue by ColinMulcahy** [bitfocus/companion-module-bmd-hyperdeck#44]
Hi,

Is it possible to implement the following features:

**ACTION**

Set the required input:

211 configuration:↵
audio input: {“embedded”, “XLR”, “RCA”}↵
↵

**FEEDBACK**

Get the selected input:

The "configuration" command may be used to query the current configuration of the deck:

configuration↵

The server returns the configuration of the deck:

configuration: audio input: {“embedded”, “XLR”, “RCA”}↵

**Comment by sphlabs** [comment]
For feedback, this will require an update to the hyperdeck-connection module to support notification of configuration changes.

nrkno/tv-automation-hyperdeck-connection#13

**Comment by sphlabs** [comment]
The Action already exists, but is only available when connected to a device that have more than one input (e.g. Studio Pro) and not with a device that only has embedded audio (e.g. Mini).
