### ISSUE TITLE
Feature Request: Clip Count - Dynamic Variable

### ISSUE THREAD

**Issue by ColinMulcahy** [bitfocus/companion-module-bmd-hyperdeck#47]
Hi,

Is it possible to implement the following features:

**DYNAMIC VARIABLE**

$(Hyperdeck:clipCount)

The "clips count" command returns the number of clips on the current timeline:

clips count ↵

The server responds with the number of clips:
214 clips count: ↵
clip count: {Count}↵

**Comment by sphlabs** [comment]
`$(Hyperdeck:clipCount)` variable now available
