### ISSUE TITLE
Preview Enable / Disable

### ISSUE THREAD

**Issue by empyfree** [bitfocus/companion-module-bmd-hyperdeck#50]
Would it be possible to add in commands to enable and disable the preview function on the Hyperdeck?

`preview: enable: true` and `preview: enable: false`

Currently if you play a clip back there's no way of returning the transport to the "preview" state to enable you to monitor incoming signals and start a new recording.

**Comment by sphlabs** [comment]
This feels like it should be a config option rather than a button action. Are there any situations where one would want to toggle this on a button?

**Comment by empyfree** [comment]
Sure.  On the hardware hyperdeck pressing the “input” button performs this action. 

In my use case I have a hyper deck somewhere in a rack. I have the output of the deck routed to a monitor in front of me.  While recording i can see what’s passing “through” the deck.  

If I hit play then the last recorded clip starts playing back. 

When I now hit “stop” the deck does not go back to previewing it’s input, rather it cues the clip up again for playback.  Right now I have to haul myself up, find the hyper deck and press the input button.  Or disable the hyper deck instance, enable the simple tcp instance and send the command that way.  

It’s not so much a setup option as it needs sending each time you play back a clip.

**Comment by Mawenzhong** [comment]
Hello, how to use it

**Comment by thumperdisney** [comment]
+1 for this request.  It is very important when using multiple HyperDeck mini units together as they won't all go into record when requested if not in preview to begin with.  The command is straight forward, the manual shows it as:  preview: enable: {true/false}  and that would let us tie it to a button if we want or make a button just for that.
