### ISSUE TITLE
Feature request : clip name variable

### ISSUE THREAD

**Issue by LYMPIA** [bitfocus/companion-module-bmd-hyperdeck#52]
Hello there !

Would it be possible to display the clip name through a variable ? For now, only the clip number can be displayed but not the filename. Having the filename pulled through a variable (ie. clip number) would be very useful.

Thanks in advance for any replies or consideration regarding this request.

**Comment by gmcgrath86** [comment]
+1 for this request.  this would be extremely helpful to ensure that the correct clip is being triggered.  please and thank you!

**Comment by airikhungri** [comment]
Any news on this? This would make it possible to set up a page with reliable video playback buttons. Making a liveproduction adjustable in the last seconds. Say a customer wants to add a new video/graphic during a pause of the show. 

To be able to prepare the content and load it through ftp and than have its name automaticly pop up on a button would be extremely powerful.

**Comment by thumperdisney** [comment]
+1 for this request.  I can think of at least a few reasons this would be helpful.  It could still be using the clip number for all command purposes but the clip name being available for button text would be great, especially if you could specify certain characters in the string of a name to be used (say the first 5-8 characters only)

**Comment by sphlabs** [comment]
Latest beta now has a `clipName` variable to display the name of the current clip.

**Comment by gmcgrath86** [comment]
Thanks very much for taking the time to work on this feature!  Is is possible to also display the name of each clip on the SD card as opposed to just the current clip?  Something along the lines of clipName_1, clipName_2, clipName_x...  This would allow for a page to be created with all of the clips displayed by name which would be extremely helpful for ensuring the clips are in the correct order, as well as easily allow the playback order to be modified on the fly.  Thanks again for your time and consideration!

**Comment by sphlabs** [comment]
This is already possible as well in the latest release.

**Comment by gmcgrath86** [comment]
Awesome thats great to hear.  I'm testing this out today, but can't seem to get it working.  The primary "clipName" variable seems to work great, but not the extension to display names of each clip individually.  Could you please confirm the formatting of the variable when you have a chance?  I've tried clipName1, clipName01, clipName_1, clipName_01, clipName-1, clipName-01, all without success.  Sorry to keep bugging you about this, we're just very excited to implement this feature!

**Comment by petertapmedia** [comment]
> This is already possible as well in the latest release.



> Awesome thats great to hear. I'm testing this out today, but can't seem to get it working. The primary "clipName" variable seems to work great, but not the extension to display names of each clip individually. Could you please confirm the formatting of the variable when you have a chance? I've tried clipName1, clipName01, clipName_1, clipName_01, clipName-1, clipName-01, all without success. Sorry to keep bugging you about this, we're just very excited to implement this feature!

I'm wondering the same thing. Adding media to the hyperdeck, where buttons are already programmed say as Play ID 1... using a variable Clipname of ID1 ID2 ID3 etc etc.....is this already possible. can't seem to figure this out.

**Comment by gaetanfromdolive** [comment]
Petertapmedia, try $(hyperdeck:clip1_name)
