### ISSUE TITLE
bitfocus compannion set up for bmd hyperdeck

### ISSUE THREAD

**Issue by pastordcarey** [bitfocus/companion-module-bmd-hyperdeck#55]
I have purchased elgato stream deck and have successfully connected to BMD Atem mini switcher (NO Problems)  i also want to connect to my Hyperdeck studio mini's. i have done manual ip's the whole setup subnets every thing. no luck in connecting. i tried DHCP no luck . both ways i am able to ping the ip on hyperdeck and connection returns packets from my computer.  i have this same setup in another bldg with another network and i can add them to that network so i know the hyperdeck are communicating.  i have removed them from a dhcp router and just set up privarte network on a switch using my mac Ethernet port. do i have to be on a dhcp server. Because i think my other bldg is just a standard switch. At this point i am at a loss  i have an event coming up the 18th and i need this to be set up.

Thanks in advance

**Comment by sphlabs** [comment]
Do you have any other devices connected to the Hyperdecks — like the ATEM? Hyperdecks only allow one connection at a time, so if one has a connection already it will refuse all others.

What is the status message you get in Companion, and are there any errors or warnings in the log?

**Comment by pastordcarey** [comment]
status on instances says connecting  i disconnect atem and still will not connect to hyperdeck

**Comment by LYMPIA** [comment]
Never had any problem connecting Hyperdeck with Companion. On some show, we run up to 11 of them at the same time. We're using strict static unique IP connections & switches in order to control/manage properly each units. Your problem sounds like it could be an IP conflict of some kind.

**Comment by sphlabs** [comment]
@pastordcarey did you manage to solve you connection issues?

**Comment by pastordcarey** [comment]
Found out that the bmd hyper deck was faulty so had to send to bmd for repair.

David Carey
________________________________

**Comment by sphlabs** [comment]
Glad you got to the bottom of it.
