### ISSUE TITLE
bmd-hyperdeck enhancement request; Audio Channels set

### ISSUE THREAD

**Issue by PhotoJoseph** [bitfocus/companion-module-bmd-hyperdeck#56]
Hey folks. The bmd-hyperdeck (Blackmagic Design HyperDeck) module is fantastic. Use it every day. One feature it doesn't have that I'd love to see is Audio Channels set. Whenever the HyperDeck reboots, or changes out of ProRes and back in, the Audio Channels default to 16 channels. Which is at best annoying, and at worse terrifying, as once I though I had no audio because it was hidden in channels 1-2 while QT Player was playing something else! Anyway if this is controllable, to be able to choose Audio Channels just like we can choose Codec could be awesome. 

![IMG_7537](https://user-images.githubusercontent.com/78106443/137004802-1935f937-264f-4ef8-91ca-b6e75965eff1.jpeg)

**Comment by sphlabs** [comment]
This is supported in the API so should be possible to implement.

**Comment by PhotoJoseph** [comment]
Awesome!! Happy to test if needed.

**Comment by PhotoJoseph** [comment]
Hey there @sphlabs did you ever happen to try to do this? Would still love this feature! The number of items I inadvertently end up with 14 channels of blank audio is astounding ;-)

**Comment by sphlabs** [comment]
@PhotoJoseph if you are able to build a dev version, could you give this a test and let me know your thoughts? If not I can build a copy and send it over to you.

**Comment by PhotoJoseph** [comment]
Hey @sphlabs! I don't know how to do that, sorry. This is where I admit I'm just a user and don't know the first thing about coding ;-) I am scrambling to get ready for NAB and leaving early tomorrow morning so I may not be able to test until I get back on Thursday, but I'm very excited to try this out!

**Comment by PhotoJoseph** [comment]
@sphlabs my hero!
