### ISSUE TITLE
HyperDeck Studio Mini timecode not updating

### ISSUE THREAD

**Issue by isaiahfranco** [bitfocus/companion-module-bmd-hyperdeck#58]
The timecode variable from my HyperDeck Studio Mini isn't updating in real time anymore. Running 2.2.0-5d942042-3642 and experiencing the same issue across different decks and different computers.

**Comment by sphlabs** [comment]
What setting do you have selected for the Timecode Variables in the instance configuration? The Mini should support Notifications ok, but Polling would also work.

**Comment by gmcgrath86** [comment]
I have also experienced this issue.  $(hyperdeck:countdownTimecodeHMSF) and $(hyperdeck:timecodeHMSF) seem to work, but none of the other timecode variables would display anything

**Comment by sphlabs** [comment]
Can you provide a screenshot of what you are seeing on the variables page?

**Comment by sphlabs** [comment]
Thi should be fixed in the latest update.
