### ISSUE TITLE
Feature Request: Clip Countdown Timer

### ISSUE THREAD

**Issue by gmcgrath86** [bitfocus/companion-module-bmd-hyperdeck#60]
If using the Hyperdeck as a video playback system, it would be extremely useful to have a variable for a countdown timer of the length of the individual video clips.  We'd like to switch away from using VLC as our video playback system (which does have this feature in the module) to using hyperdecks, however not having a clip countdown timer is one of the major reasons holding us back from doing so.  Timecode alone is not very useful in this context.  Please and thank you!

**Comment by sphlabs** [comment]
You can already do this with the countdown timecode variables. They provide remaining time of the current clip.

**Comment by gmcgrath86** [comment]
Ahh my apologies, I see what I did wrong here.  The timeline output on the hyperdeck itself needs to be set to "timeline" instead of "clip" in order for the countdown timer on the stream deck to count down the individual clips.  Setting it to "clip" will display a countdown of the total length of all the clips added together.  All set now, thanks!
