### ISSUE TITLE
Balckmagic Hyperdeck

### ISSUE THREAD

**Issue by Westra72** [bitfocus/companion-module-bmd-hyperdeck#67]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

 Clip list functionality for BM Hyperdeck

### Usecases

I would like clip list functionality if possible for the Hyperdeck

**Comment by sphlabs** [comment]
Could you explain what you mean by 'clip list functionality'?

**Comment by Westra72** [comment]
Welcome Stephen!

I thought that a button would contain a list of clips that could be
modified in content and play mode.
Something like this:
- play Next -> plays the next Clip or the first when there is no next Clip
-
goto Next -> stops and then selects the next Clip or the first when there
is no next Clip
-
Pause on last Frame -> Pauses the current clip on the last frame
-
Go to first Frame -> Stops the Video and goes to the first Frame of the
Video
- It would also be nice if you could write the name of the file on the
button, not just the number of the clip.
- Best regards
- Peter


Stephen Harrison ***@***.***> ezt írta (időpont: 2022. márc.
10., Cs, 12:18):

**Comment by Westra72** [comment]
Welcome stephen!

Maybe there could be an available action (button combination) like aja kipro
such as:
Load Clip By Name (Requires extension)
Load Clip By List--> I think this is a really useful thing 

Thanks!

Peter

**Comment by sphlabs** [comment]
Could you try out the latest beta and see if it covers what you are after? It is now possible to select clips by name from a list and there are clip name variables for display.
