### ISSUE TITLE
HyperDeck 12G never connects

### ISSUE THREAD

**Issue by angelsix** [bitfocus/companion-module-bmd-hyperdeck#69]
I am having issues and tried on several computers. The HyperDeck 12G which is on the network, is found by ATEM software perfectly file, even with or without ATEM open, power cycling the HyperDeck and restarting Companion/readding connection etc... it is always in a Connecting... state.

I get it to show OK very rarely, if I turn everything off, restart PC, start Companion first, then start HyperDeck, it sometimes then connects. It is incredibly rare it works.

My network is Unifi and has everything open for the connections to work. Notably I have a subnet mask of 255.255.252.0 as I run over into 192.168.3.x IP addresses, and both the computer (Mac and tried Windows) running Companion are on the 192.168.3.x network. ATEM Television Studio 4k always connects instantly no problem

**Comment by sphlabs** [comment]
@angelsix Is this a duplicate of #71 ?

**Comment by angelsix** [comment]
Yep
