### ISSUE TITLE
Feature Request: Adding module for Hyperdeck Shuttle

### ISSUE THREAD

**Issue by trevorf321** [bitfocus/companion-module-bmd-hyperdeck#70]
The Hyperdeck shuttle has some unique feature that would be awesome to control from companion

**Comment by sphlabs** [comment]
I presume you are referring to the autocue features, as I think most other things are covered by existing actions.

It would certainly be good to add full support for the shuttle, but at the moment I don't have access to one for development, which makes things somewhat harder.

**Comment by sphlabs** [comment]
Basic support for the Shuttle is now added
