### ISSUE TITLE
HyperDeck Studio HD Plus Clip List

### ISSUE THREAD

**Issue by LHasenbein** [bitfocus/companion-module-bmd-hyperdeck#73]
Hello everybody.
With my HyperDecks, the clip list is not updated, but the clip count is. Example: If I don't insert an SD card and start Companion, the clip list is of course empty. If I then insert a card, nothing changes. The list remains empty. The clip count changes. Only when I close Companion and start it again, the list does appear completely.
I use 2.3.0 (2.3.0+4520-beta-a4e368fd) on an Intel Mac and M1

**Comment by sphlabs** [comment]
This should be fixed with the latest beta release
