### ISSUE TITLE
[Feature Request] Hyperdeck Shuttle Codec switching (between H264 and Teleprompter)

### ISSUE THREAD

**Issue by NickKHarrison** [bitfocus/companion-module-bmd-hyperdeck#75]
Hi there, a huge workflow improvement for the Hyperdeck module would be the ability to change to more codecs. Currently, we have five QuickTime codecs and two DNxHD codecs. On the Shuttle hardware, the missing codecs in the "Codec" menu are:

Under the H.264 header (in Codec menu):
H.264 High
H.264 Medium
H.264 Low

Under the Teleprompter header (in Codec menu):
Teleprompter

The big improvement in adding these is being able to quickly switch between Teleprompter mode and video mode - instead of menu diving on the hardware. I currently have Companion setup using the hyperdeck module to control my Shuttle. I'm using the Press Action "hyperdeck: File format" to select QuickTime ProRes and this allows me to move me from Teleprompter mode to video mode (with the ProRes format set). If we had the option to select the Teleprompter 'Codec' then we could easily switch between modes.

Would greatly appreciate if someone could add the option to select the missing codecs.

**Comment by Runee** [comment]
This feature would be greatly appreciated. As of now, we are only using the HyperDeck Shuttle as a teleprompter merely because we cannot expect our users to dive into (tiny) menus on the hardware in order to switch functionality.

Keeping my fingers crossed!

**Comment by sphlabs** [comment]
This is now possible with the latest update.
