### ISSUE TITLE
Feature request: Set date and time in HyperDecks

### ISSUE THREAD

**Issue by PhotoJoseph** [bitfocus/companion-module-bmd-hyperdeck#76]
The internal clock on the Hyperdeck gets reset whenever you connect it to a computer, but it drifts faster than a Tokyo street racer. I'd love to see a way to set the date/time to current on demand!

**Comment by PhotoJoseph** [comment]
Bump.

**Comment by sphlabs** [comment]
Unfortunately, there is no published API for setting date and time, so I don't think this is possible. There are commands to toggle the appending of a timestamp to filenames, and the timecode preset can be set, but not the clock.

**Comment by PhotoJoseph** [comment]
ah, that's really a shame. OK, thank you for looking into that.
