### ISSUE TITLE
[Bug] Hyperdeck Studio 4K Pro perpetually Connecting

### ISSUE THREAD

**Issue by ZachIndigo** [bitfocus/companion-module-bmd-hyperdeck#78]
We use two of these, on the same network, with a mac running companion, and several other blackmagic devices and computers that are not set to connect to the decks in any way.

Companion will perpetually say "Connecting" for these devices, which seems to indicate that they are already connected to something else; however, while companion is trying to connect to them, I can directly connect to them using the HyperDeck controller software via Bottles on Linux, configure them, disconnect, and at no point will companion connect to them, or (on the same Mac) I can connect to them using the ATEM Control software, and then disconnect, and again companion will never connect.

I captured logs from starting companion, deleting the hyperdeck from the devices, adding it back in, and waiting a while.:jma

This is the output from the companion binary:

[companion.log](https://github.com/bitfocus/companion-module-bmd-hyperdeck/files/10253115/companion.log)

This is the exported log from companion:

[companion.log.log](https://github.com/bitfocus/companion-module-bmd-hyperdeck/files/10253116/companion.log.log)

Neither seem to have anything to indicate an issue.

**Comment by Julusian** [comment]
Hopefully this was related to #90. If not, then more information is needed to be able to progress
