### ISSUE TITLE
Single clip playback not working

### ISSUE THREAD

**Issue by LHasenbein** [bitfocus/companion-module-bmd-hyperdeck#80]
The "Single clip playback" option does not work anymore. I can click it, but nothing happens. Last time it worked for me in version 5401 (HyperDeck Studio HD Plus)

**Comment by LikeThisReview** [comment]
This [BUG] is still present in Companion v3.0.0+5584 and hyperdeck v.2.0.1 and using HyperDeck Studio HD Plus. Play Loop Clip single clip playback loops all clips on the disk. (At the same time there is no action for the the Clip Mode button for the Hyperdeck Shuttle. This is not an enhancement request. Regards Nico Wasmus

**Comment by sphlabs** [comment]
Thanks for the bug report; this has not been patched.

@LikeThisReview I'm not sure what you mean about the Clip Mode button? If this is a different issue could you open a new issue for it please?

**Comment by LikeThisReview** [comment]
Thanks Stephen, The reference to Clip Mode was for references only.
The Blackmagic Design Hyperdeck Shuttle has a Clip mode button, press this
button and the Play button will play 1 clip only. But it is not important-
what we need is a way to play one clip only. How it is implemented in
Hyperdeck module is just fine.

Regards, Nico


Op wo 1 feb. 2023 om 23:02 schreef Stephen Harrison <
***@***.***>

**Comment by sphlabs** [comment]
Ok, I understand now and, as you say, it's not a problem. Companion is not tying to reproduce the button presses made on the physical devices, just provide the functionality!

**Comment by LHasenbein** [comment]
@sphlabs > Thanks for the bug report; this has now been patched.

thank you very much. But I tried the latest beta and developer builds of companion, single clip loop still doesn't work for me. It's looping, but not single clip looping.

**Comment by sphlabs** [comment]
There's a new build available now -- 5640 -- that should include the fixes. See how you get on with that one.

**Comment by LikeThisReview** [comment]
Thank you very much. (play all, Loop all), Play 1 clip, loop 1 clip, and
feedback works all fine for me in this build.

Op ma 6 feb. 2023 om 21:56 schreef Stephen Harrison <
***@***.***>:

**Comment by LHasenbein** [comment]
> There's a new build available now -- 5640 -- that should include the fixes. See how you get on with that one.

@sphlabs All good for me now. Thank you very much. :)
