### ISSUE TITLE
Hyperdeck Shutlle HD

### ISSUE THREAD

**Issue by Suenee** [bitfocus/companion-module-bmd-hyperdeck#81]
HW: Hyperdeck Shuttle HD
Companion: [2.4.1 (2.4.1+4898-v2-4.1-9646192a)](https://bitfocus.io/companion/)

It is possible to call PLAY, STOP, RECORD. The PREVIEW option is missing, even if the status is detected in the feedback.

Ways to get around it:
1. press the "REC" button on the HD.
2. start recording to and stop it immediately. (use the same file always)

Both are user-unfriendly.

**Comment by sphlabs** [comment]
There is a dedicated **Preview** action that should be available (between **Select (slot)** and **Video source**). Is that not showing up for you?

I don't have a Shuttle with me at the moment to test, but as far as I know that should be there.

**Comment by Suenee** [comment]
> There is a dedicated **Preview** action that should be available (between **Select (slot)** and **Video source**). Is that not showing up for you?
> 
> I don't have a Shuttle with me at the moment to test, but as far as I know that should be there.

As I wrote above **PREVIEW** is not avaliable in actions. You can detect only feedback state.

**Comment by sphlabs** [comment]
I have my shuttle back and have re-tested this now and there is most certainly a Preview action available and it functions correctly.

Could you try looking through the full list of actions again, as I can't see any reason why it wouldn't be showing for you.

**Comment by Suenee** [comment]
> I have my shuttle back and have re-tested this now and there is most certainly a Preview action available and it functions correctly.
> 
> Could you try looking through the full list of actions again, as I can't see any reason why it wouldn't be showing for you.

Hi, I don't understand how this could happen. I'm trying it now on my home computer and there is indeed a HYPERDECK:PREVIEW action. I have to check it out at work on their local tech as well.
Thanks for support. :-)
