### ISSUE TITLE
Feature request: Runtime Clip + Filename without extension

### ISSUE THREAD

**Issue by AlivonBali** [bitfocus/companion-module-bmd-hyperdeck#84]
Hi.
Is it possible to get a countdown for the runtime of a Clip. I use the Hyperdeck most of the time just for playback and it would be nice to have a counter and countdown for the runtime of the Clip which is running. And a second request, I love it to see the filename on the stream deck, but it is possible to show it without the extension. At the moment ist shows "intro.mov" so it just shows "intro".

Thank you
Alex

**Comment by sphlabs** [comment]
There are a number of countdown variables that will give you what you want; have a look in the Variables tab. You have a choice of `countdownTimecodeH`, `countdownTimecodeM`, `countdownTimecodeS`, `countdownTimecodeF`, `countdownTimecodeHMS`, `countdownTimecodeHMSF`.

You will need to enable timecode variables in the instance configuration page. Depending on the model you are using select Polling or Notifications. Early models need Polling but anything from the first HyperDeck Mini 4k or newer work with Notifications.

The work to strip file extensions has already been done, but it didn't make it into the 2.4 release cycle. It is available in 3.0, although that is very much still in beta.
