### ISSUE TITLE
New Command - Spill Recording

### ISSUE THREAD

**Issue by Beaumon6** [bitfocus/companion-module-bmd-hyperdeck#85]
Hello,

Is there anyway to add the following commands to the Blackmagic Hyperdeck connection?

record spill  - spill current recording to next slot
record: spill: slot id: {n} -  spill current recording to specified slot / use current id to spill to same slot

We believe that this will create a new file and continue the recording. We want to spill the file every 20 min so we are doing this by long pressing the record button on the deck. This would allow us to do it remotely. ;)

Thank You

**Comment by Beaumon6** [comment]
Hello, we found an error in the manual. These are the correct commands:

record spill - spill current recording to next slot
record spill: slot id:{n} - spill current recording to specified slot / use current id to spill to same slot

Removed one of the ":" and the space before the number in the 2nd command.

**Comment by sphlabs** [comment]
My understanding (backed up by testing) is that the record spill command is used to determine what happens when the current drive fills up. Issuing a `record spill` command while recording does not create a new file.

The reason it is possible to specify the same slot for record spill is in the case of a connected Multi Dock, where there can be up to 4 SSD drives on the one Hyperdeck slot.

So the function can be added to Companion, but it won't do what you are hoping.

**Comment by Beaumon6** [comment]
We are able to issue this command over Telnet and it does exactly what we need. It stops the current file and starts a new one. One will do it on the next drive available but the second command can be set to use the current drive that is being recorded to, basically ending the file and starting a new one.

Then we FTP into the drive and start copying the file that was just ended as the show continues.

This all worked, just hoping to get the companion buttons to do this rather than sending text commands to each deck via telnet.

**Comment by sphlabs** [comment]
I'm not sure why I wasn't seeing that behaviour when I did my previous tests (no doubt operator error), but I've just re-tested this and am getting the same result as you, with a new file being created.

**Comment by Beaumon6** [comment]
That is awesome news!

**Comment by Beaumon6** [comment]
@sphlabs Hi, sorry for the noob question, but if this gets added to Companion, how will I know?

**Comment by Julusian** [comment]
This is implemented, and will be in the beta builds later today
