### ISSUE TITLE
Feature Request: Show Hyperdeck Recording Duration

### ISSUE THREAD

**Issue by kateRISE** [bitfocus/companion-module-bmd-hyperdeck#89]
Hi there! For the purpose of being able to mark notable moments during a recording we need to see the current recording duration—not just the amount of available recording time left. Is there any way to do this? We currently have a blank OBS recording that we use just to get the time stamp, but it would be so much better if we can pull the timestamp that's present on the Hyperdeck screen. Thanks!

**Comment by magdatev** [comment]
Have you ever tried it with the timecode? 

$(Hyperdeck 1:timecodeHMSF)\n($(Hyperdeck 1:recordingTime))

**Comment by sphlabs** [comment]
As noted, the `timecode` variables will show the current clip time for recording, as well as playback. It essentially replicates the display timecode on the device.

So, e.g. `$(hyperdeck:timecodeHMS)` would show you the current recording time to the nearest second.
