### ISSUE TITLE
ProtocolVersion checks broken

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion-module-bmd-hyperdeck#90]
Possibly a duplicate of #78?

The check at https://github.com/bitfocus/companion-module-bmd-hyperdeck/blob/2da5dabaacf5584fb18b759cdb3974d35428c46a/index.js#L311 does not work correctly.
I have a hyperdeck running 1.8, which is older than 1.11 but is caught in this if statement causing the connection to get stuck in a crash loop

I haven't checked for similar issues elsewhere in the code

**Comment by sphlabs** [comment]
This only occurred when trying to set an older (pre-1.11) device to use Notifications, which I hadn't tried to do on my OG Studios as I knew it wasn't supported! ;-)

Should be fixed now.

**Comment by Julusian** [comment]
Yeah I found it while trying to figure out why the module got stuck in a crash loop on a pair of something 4k.
The real crash was fixed by a commit pushed in February that hasn't been pulled into the builds.

This may or may not have been a factor, but I found it when trying to reproduce that crash

**Comment by sphlabs** [comment]
Well a good catch. Took a moment to realise that treating versions as numbers doesn't work for very long!
