### ISSUE TITLE
Hyperdeck video format not working for DNx220 MXF

### ISSUE THREAD

**Issue by TrevorAyl** [bitfocus/companion-module-bmd-hyperdeck#91]
Using ShuttleHD with Companion emulator:

Setting a button to action hyperdeck: File format - works for all the flavours other than DNx220, (possibly because it needs an x?)

These are the flavours that work via telnet

> QuickTimeDNxHD220x QuickTimeDNxHD145 QuickTimeDNxHD45
> DNxHD220x DNxHD145  DNxHD45

Not sure if this is the offending code (sorry very limited skills)

> index.js:
>   87  			{ id: 'QuickTimeProResProxy', label: 'QuickTime ProRes Proxy', family: 'proxy' },
>   88: 			{ id: 'QuickTimeDNxHD45', label: 'DNxHD 45 QT', family: 'DNx' },
>   89: 			{ id: 'DNxHD45', label: 'DNxHD 45 MXF', family: 'DNx' },
>   90: 			{ id: 'QuickTimeDNxHD145', label: 'DNxHD 145 QT', family: 'DNx' },
>   91: 			{ id: 'DNxHD145', label: 'DNxHD 145 MXF', family: 'DNx' },
>   92: 			{ id: 'QuickTimeDNxHD220', label: 'DNxHD 220 QT', family: 'DNxHD220' },
>   93: 			{ id: 'DNxHD220', label: 'MXF DNxHD 220', family: 'DNxHD220' },
>   94  			{ id: 'QuickTimeDNxHR_HQX', label: 'DNxHR HQX QT', family: 'DNxHR_HQX' },

and a possible solution: 

> 
> index.js:
>   87  			{ id: 'QuickTimeProResProxy', label: 'QuickTime ProRes Proxy', family: 'proxy' },
>   88: 			{ id: 'QuickTimeDNxHD45', label: 'DNxHD 45 QT', family: 'DNx' },
>   89: 			{ id: 'DNxHD45', label: 'DNxHD 45 MXF', family: 'DNx' },
>   90: 			{ id: 'QuickTimeDNxHD145', label: 'DNxHD 145 QT', family: 'DNx' },
>   91: 			{ id: 'DNxHD145', label: 'DNxHD 145 MXF', family: 'DNx' },
>   92: 			{ id: 'QuickTimeDNxHD220x', label: 'DNxHD 220x QT', family: 'DNxHD220x' },
>   93: 			{ id: 'DNxHD220x', label: 'DNxHD 220x MXF', family: 'DNxHD220x' },
>   94  			{ id: 'QuickTimeDNxHR_HQX', label: 'DNxHR HQX QT', family: 'DNxHR_HQX' },

Apologies for any faux pas I've committed...

**Comment by LikeThisReview** [comment]
Not sure there is an issue here.
As I have no experience with DNx please review following test results on HyperDeck Studio HD Plus.

configuration: file format: DNxHD220x
200 ok
configuration
211 configuration:
(…)
file format: DNxHR_HQX


configuration: file format: DNxHR_HQX
200 ok
configuration
211 configuration:
(…)
file format: DNxHR_HQX

In summary: 
DNxHD220x returns DNxHR_HQX
DNxHR145 returns DNxHR-SQSQ MXF
DNxHD45 returns DNxHR_LB 

In Companion action "hyperdeck: File format" uses for example "DNxHR LB MXF" and variable $(hyperdeck:fileFormat) is set accordingly (and tcp shows DNxHR_HQX, DNxHR-SQSQ MXF, and DNxHR_LB ).

- Nico Wasmus

**Comment by Julusian** [comment]
This appears to be a case of old models support `DNxHD220`, the shuttle supports `DNxHD220x` and the newer hd range claims to support `DNxHD220x`, but it is actually an alias for `DNxHR_HQX`.

Blackmagic do like to make these things complicated, especially as there is no way to query a particular device to find out what it supports...

Of course, this is assuming that the documentation pdf is correct and that isnt a typo

**Comment by Julusian** [comment]
This should be fixed in the next beta build.

**Comment by LikeThisReview** [comment]
This works fine for me on HyperDeck Studio HD Plus. Thanks!

Op vr 6 okt 2023 om 21:10 schreef Julian Waller ***@***.***>:
