### ISSUE TITLE
Controlling shuttle speed using rotary knobs on new stream deck plus

### ISSUE THREAD

**Issue by Offairwithjez** [bitfocus/companion-module-bmd-hyperdeck#96]
Looking for a way to fastforward and rewind using the rotary knobs on a stream deck plus with varying speed during rotation. with rewind to the left and fast forward to the right.

**Comment by peternewman** [comment]
See also some discussion in https://github.com/bitfocus/companion/pull/2436

The module has support for speed already:
https://github.com/bitfocus/companion-module-bmd-hyperdeck/blob/1d7b57423476c9f09f4c44e45fef25e2f8036b67/actions.js#L313-L331

The Streamdeck module just fires off the rotate command:
https://github.com/bitfocus/companion/blob/126f27e807ffbbeb1f420702b12b315bcfa7ea67/lib/Surface/USB/ElgatoStreamDeck.js#L106-L111

So for now you'd need to have a custom variable for each knob, start with it zeroed and then increment or decrement depending on the rotation direction.

However given it doesn't spring back like a proper shuttle wheel, you'll need to also zero the variable (and maybe explicitly stop the shuttle) when you press another command to cancel out like pause or stop or play.
