### ISSUE TITLE
Recording Time Remaining is set incorrectly set to —:—:—

### ISSUE THREAD

**Issue by LikeThisReview** [bitfocus/companion-module-bmd-hyperdeck#97]
Recording Time Remaining is set incorrectly set to —:—:—
$(hyperdeck:recordingTime), $(hyperdeck:slot1_recordingTime), $(hyperdeck:slot1_recordingTime) and $(hyperdeck:slot1_recordingTime) often incorrectly indicate —:—:— while there actually is a recoding time available (for example slot info indicates “recording time: 10799”). Observed that when the codec is changed, suddenly the correct recording time is displayed.

**Comment by Julusian** [comment]
I may have fixed this accidentally, but this isnt happening for me following some other changes I have made. Could you give this a retest once the updated module is in the beta builds?

**Comment by LikeThisReview** [comment]
Julian, Looks like you fixed it! Many thanks!!

Op vr 6 okt 2023 om 21:12 schreef Julian Waller ***@***.***>:
